/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project_final2;

/**
 *
 * @author tingchen
 */
import com.aetrion.flickr.FlickrException;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;

import project_final2.Beatbox;
public class PICUI extends javax.swing.JFrame {

    
    String globalkeyword;
    /**
     * Creates new form PICUI
     */
    public PICUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        keyword = new javax.swing.JTextArea();
        gobeat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HEAR, WATCH IT");
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        keyword.setColumns(20);
        keyword.setRows(5);
        jScrollPane1.setViewportView(keyword);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 350, 244, 84);

        gobeat.setFont(new java.awt.Font("Marion", 1, 80)); // NOI18N
        gobeat.setForeground(new java.awt.Color(255, 51, 51));
        gobeat.setText("GO");
        gobeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobeatMouseClicked(evt);
            }
        });
        getContentPane().add(gobeat);
        gobeat.setBounds(470, 310, 160, 180);

        jLabel2.setFont(new java.awt.Font("Marlett", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage1/back1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobeatMouseClicked
        // TODO add your handling code here:
        Beatbox testbeat = new Beatbox();
        testbeat.buildGUI();
        this.setVisible(false);
        
 //      add the load img part 
        
    //    try {
            // TODO add your handling code here:
            String keyword;
            try {
                keyword = this.keyword.getText();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "bad first keyword", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

         //   flickrfinal testhere = new flickrfinal();
            //testhere.testimg(keyword);
         //   return;
   //     } 
            /*catch (ParserConfigurationException ex) {
            Logger.getLogger(PICUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PICUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(PICUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FlickrException ex) {
            Logger.getLogger(PICUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/


    }//GEN-LAST:event_gobeatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PICUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gobeat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea keyword;
    // End of variables declaration//GEN-END:variables
}
