/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mypackage1;

/**
 *
 * @author tingchen
 */
import com.aetrion.flickr.FlickrException;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;

import mypackage1.Beatbox;

import org.xml.sax.SAXException;
public class PICUI extends javax.swing.JFrame {

    
    String globalkeyword;
    /**
     * Creates new form PICUI
     */
    public PICUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sad = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HAPPY = new java.awt.Checkbox();
        Plain = new java.awt.Checkbox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HEAR, WATCH IT");
        setBounds(new java.awt.Rectangle(0, 22, 1100, 500));
        setMaximumSize(new java.awt.Dimension(1100, 500));
        setMinimumSize(new java.awt.Dimension(1100, 500));
        getContentPane().setLayout(null);

        Sad.setBackground(new java.awt.Color(0, 0, 0));
        Sad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SadMouseClicked(evt);
            }
        });
        getContentPane().add(Sad);
        Sad.setBounds(880, 430, 20, 20);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOW ARE YOU FEELING TODAY?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 1070, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage1/PLAIN.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 210, 230, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage1/HAPPY.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 210, 240, 220);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage1/BAD MOOD.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 180, 240, 280);

        HAPPY.setBackground(new java.awt.Color(0, 0, 0));
        HAPPY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HAPPYMouseClicked(evt);
            }
        });
        getContentPane().add(HAPPY);
        HAPPY.setBounds(190, 430, 20, 20);

        Plain.setBackground(new java.awt.Color(0, 0, 0));
        Plain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlainMouseClicked(evt);
            }
        });
        getContentPane().add(Plain);
        Plain.setBounds(540, 430, 20, 20);

        jLabel2.setFont(new java.awt.Font("Marlett", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage1/back1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1190, 500);

        pack();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }// </editor-fold>//GEN-END:initComponents

    private void HAPPYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HAPPYMouseClicked
        // TODO add your handling code here:
        Beatbox test = new Beatbox(3);
        test.buildGUI();
        this.setVisible(false);
    }//GEN-LAST:event_HAPPYMouseClicked

    private void PlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlainMouseClicked
        // TODO add your handling code here:
        Beatbox test = new Beatbox(2);
        test.buildGUI();
        this.setVisible(false);
    }//GEN-LAST:event_PlainMouseClicked

    private void SadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SadMouseClicked
        // TODO add your handling code here:
        Beatbox test = new Beatbox(1);
        test.buildGUI();
        this.setVisible(false);
    }//GEN-LAST:event_SadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PICUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PICUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox HAPPY;
    private java.awt.Checkbox Plain;
    private java.awt.Checkbox Sad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
